### PR TITLE
Fix/extension post

### PR DESCRIPTION
**Pull request by andresgnlez**

### CODE REVIEW

**Comment by andresgnlez** [comment]
Hey @shanikadhettige,

I just notice latest chapters you have uploaded didn't have file extension. I just fix that.

**Comment by shanikadhettige** [comment]
Thanks @andresgnlez, still not seeing it on http://vizzuality.github.io/community-mapping/ though. Could you explain how to make that happen?

**Comment by andresgnlez** [comment]
Oh, for seeing it there I have to deploy previously. I thought the work wasn't finished that's why I didn't deploy. Shall I deploy then?

**Comment by shanikadhettige** [comment]
That would be great just to test it. Then if you could write out how Vivien and I could deploy the changes ourselves we could just add the content and deploy as soon as we can add the additional content.

**Comment by andresgnlez** [comment]
The site is updated with latest changes: https://vizzuality.github.io/community-mapping/

**Pull request merged**
